//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentingWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int ArticleId { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public string Fit { get; set; }
        public string EventType { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ImageArticle { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
    }
}
